=== zborovskaya/prEpamJava/task08XmlParsing/src/main/resources/data/candy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.zborovskaya.by/task08/entities"
        xmlns:tns="http://www.zborovskaya.by/task08/entities"
        elementFormDefault="qualified">
    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:candy"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="candy" type="tns:Candy" abstract="true"></element>
    <element name="chocolateCandy" type="tns:ChocolateCandy" substitutionGroup="tns:candy"></element>
    <element name="caramelCandy" type="tns:CaramelCandy" substitutionGroup="tns:candy"></element>

    <complexType name="Candy">
        <sequence>
            <element name="name" type="string" />
            <element name="energy" type="positiveInteger" />
            <element name="production" type="string" />
            <element name="value" type="tns:Value" />
        </sequence>
        <attribute name="marking" type="tns:Marking" use="required"/>
    </complexType>

    <complexType name="ChocolateCandy">
        <complexContent>
            <extension base="tns:Candy">
                <sequence>
                    <element name="ingredientsChocolate" type="tns:IngredientsChocolate" />
                </sequence>
                <attribute name="filling" type="string" use="optional" default="nothing">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="nothing"></enumeration>
                            <enumeration value="fruit"></enumeration>
                            <enumeration value="nutty"></enumeration>
                            <enumeration value="dairy"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="CaramelCandy">
        <complexContent>
            <extension base="tns:Candy">
                <sequence>
                    <element name="ingredientsCaramel" type="tns:Ingredients" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Value">
        <all>
            <element name="proteins" type="decimal"/>
            <element name="fats" type="decimal"/>
            <element name="carbohydrates" type="decimal"/>
        </all>
    </complexType>

    <element name="ingredients" type="tns:Ingredients" abstract="true"></element>
    <element name="ingredientsChocolate" type="tns:IngredientsChocolate" substitutionGroup="tns:ingredients"></element>
    <element name="ingredientsCaramel" type="tns:Ingredients" substitutionGroup="tns:ingredients"></element>
    <complexType name="Ingredients">
        <all>
            <element name="water" type="decimal" />
            <element name="sugar" type="decimal" />
            <element name="fructose" type="decimal" />
            <element name="vanillin" type="decimal" />
        </all>
    </complexType>

    <complexType name="IngredientsChocolate">
        <complexContent>
            <extension base="tns:Ingredients">
                <all>
                    <element name="chocolateType" type="tns:ChocolateType" />
                </all>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="ChocolateType">
        <restriction base="string">
            <enumeration value="milk"></enumeration>
            <enumeration value="dark"></enumeration>
        </restriction>
    </simpleType>
    <simpleType name="Marking">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{6,10}"/>
        </restriction>
    </simpleType>
</schema>

=== zborovskaya/prEpamJava/task08XmlParsing/src/main/resources/data/candy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.zborovskaya.by/task08/entities"
         xsi:schemaLocation="http://www.zborovskaya.by/task08/entities candy.xsd">
    <caramelCandy marking="chupa1234">
        <dateProduction>2020-09-24</dateProduction>
        <name>Chupa-Chups</name>
        <energy>380</energy>
        <production>Chupa-Chups</production>
        <value>
            <proteins>0.2</proteins>
            <fats>0</fats>
            <carbohydrates>94</carbohydrates>
        </value>
        <ingredientsCaramel>
            <water>5</water>
            <sugar>30</sugar>
            <fructose>5</fructose>
            <vanillin>5</vanillin>
        </ingredientsCaramel>
    </caramelCandy>
    <chocolateCandy marking="shapka1235">
        <dateProduction>2021-05-24</dateProduction>
        <name>Little Red Riding Hood</name>
        <energy>300</energy>
        <production>Kommunarka</production>
        <value>
            <proteins>0.3</proteins>
            <fats>0.1</fats>
            <carbohydrates>90</carbohydrates>
        </value>
        <ingredientsChocolate>
            <water>3</water>
            <sugar>20</sugar>
            <fructose>5</fructose>
            <vanillin>5</vanillin>
            <chocolateType>milk</chocolateType>
        </ingredientsChocolate>
    </chocolateCandy>
    <chocolateCandy filling="nutty" marking="nuts5678" >
        <dateProduction>2021-04-24</dateProduction>
        <name>Сhocolate covered nut</name>
        <energy>350</energy>
        <production>Kommunarka</production>
        <value>
            <proteins>0.9</proteins>
            <fats>12</fats>
            <carbohydrates>60</carbohydrates>
        </value>
        <ingredientsChocolate>
            <water>10</water>
            <sugar>15</sugar>
            <fructose>0</fructose>
            <vanillin>0</vanillin>
            <chocolateType>dark</chocolateType>
        </ingredientsChocolate>
    </chocolateCandy>
    <chocolateCandy marking="aer7234">
        <dateProduction>2021-03-24</dateProduction>
        <name>Aeroflot</name>
        <energy>350</energy>
        <production>Spartac</production>
        <value>
            <fats>8</fats>
            <proteins>0.5</proteins>
            <carbohydrates>90</carbohydrates>
        </value>
        <ingredientsChocolate>
            <water>10</water>
            <sugar>25</sugar>
            <fructose>0</fructose>
            <vanillin>0</vanillin>
            <chocolateType>dark</chocolateType>
        </ingredientsChocolate>
    </chocolateCandy>
    <chocolateCandy marking="cherry56" filling="fruit">
        <dateProduction>2021-02-24</dateProduction>
        <name>Cherry candy</name>
        <energy>230</energy>
        <production>Spartac</production>
        <value>
            <proteins>0.3</proteins>
            <fats>0.2</fats>
            <carbohydrates>59</carbohydrates>
        </value>
        <ingredientsChocolate>
            <water>10</water>
            <sugar>20</sugar>
            <fructose>0</fructose>
            <vanillin>0</vanillin>
            <chocolateType>dark</chocolateType>
        </ingredientsChocolate>
    </chocolateCandy>
    <caramelCandy marking="fizzy786">
        <dateProduction>2021-01-24</dateProduction>
        <name>Fizzy Boom</name>
        <energy>230</energy>
        <production>Roshen</production>
        <value>
            <proteins>0.2</proteins>
            <fats>0</fats>
            <carbohydrates>90</carbohydrates>
        </value>
        <ingredientsCaramel>
            <water>10</water>
            <sugar>25</sugar>
            <fructose>15</fructose>
            <vanillin>10</vanillin>
        </ingredientsCaramel>
    </caramelCandy>
</candies>

<!--
Конфеты
Name – название конфеты.
Energy– калорийность (ккал).
Type (должно быть несколько) – тип конфеты (карамель, шоколадная [с начинкой либо нет]).
Ingredients (должно быть несколько) – ингредиенты: вода, сахар (в мг), фруктоза (в мг), тип шоколада (для шоколадных), ванилин (в мг)
Value – пищевая ценность: белки (в гр.), жиры (в гр.) и углеводы (в гр.).
Production – предприятие-изготовитель.
Корневой элемент назвать Candies.
-->

=== zborovskaya/prEpamJava/task08-XMLParsing/src/main/resources/data/testCandy.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.zborovskaya.by/task08/entities"
         xsi:schemaLocation="http://www.zborovskaya.by/task08/entities candy.xsd">
    <caramelCandy marking="chupa1234">
        <dateProduction>2020-09-24</dateProduction>
        <name>Chupa-Chups</name>
        <energy>380</energy>
        <production>Chupa-Chups</production>
        <value>
            <proteins>0.2</proteins>
            <fats>0</fats>
            <carbohydrates>94</carbohydrates>
        </value>
        <ingredientsCaramel>
            <water>5</water>
            <sugar>30</sugar>
            <fructose>5</fructose>
            <vanillin>5</vanillin>
        </ingredientsCaramel>
    </caramelCandy>
    <chocolateCandy marking="shapka1235">
        <dateProduction>2021-05-24</dateProduction>
        <name>Little Red Riding Hood</name>
        <energy>300</energy>
        <production>Kommunarka</production>
        <value>
            <proteins>0.3</proteins>
            <fats>0.1</fats>
            <carbohydrates>90</carbohydrates>
        </value>
        <ingredientsChocolate>
            <water>3</water>
            <sugar>20</sugar>
            <fructose>5</fructose>
            <vanillin>5</vanillin>
            <chocolateType>milk</chocolateType>
        </ingredientsChocolate>
    </chocolateCandy>
</candies>
